using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Agrades.Data.Entities.Categories;

public enum Rasd
{
    SchoolAttendanceInRegisteredSchool = 11,
    CurrentEducationInPrimarySchoolUnderAlternateCare = 12,
    FulfillmentOfMSABy50Paragraph3 = 15,
    FulfillmentOfMSABy38Paragraph1LetterA = 21,
    FulfillmentOfMSABy38Paragraph1LetterB = 22,
    FulfillmentOfMSABy38Paragraph1LetterC = 23,
    IndividualToitionAbroadBy38Paragraph2 = 24,
    FulfillmentOfMSABy38Paragraph1LetterD = 25,
    IndividualTuitionBy41 = 30

}

public enum Rafs
{
    Daily = 10,
    LongDistance = 22,
    Afternoon = 23,
    Remote = 24,
    Combined = 30
}

public enum Rads
{
    OneYear = 10,
    OneAndAHalfYear = 15,
    TwoYear = 20,
    TwoAndAHalfYear = 25,
    ThreeYear = 30,
    ThreeAndAHalfYear = 35,
    FourYear = 40,
    FourAndAHalfYear = 45,
    FiveYear = 50,
    SixYear = 60,
    EightYear = 80,
    NineYear = 90,
    TenYear = 100,
  
}

public enum Rakz
{
    WithoutChange = 0,
    ChangeOfEducationType,
    ChangeOrganizationOfStudy,
    ConductingAnExam = 5,
    ChangeOfPersonalInfo,
    ChangeOfPersonalId,
    ChangeInConfessionsOrInProvidingSupportMeasures,
}
 

public enum Rapz
{
    ElementarySchoolFifthGrade = 1,
    ElementarySchoolSixthGrade,
    ElementarySchoolSeventhGrade,
    ElementarySchoolEighthGrade,
    ElementarySchoolNinethGrade,
    ElementarySchoolTenthGrade,
    ElementarySpecialSchoolFifthGrade,
    ElementarySpecialSchoolSixthGrade,
    ElementarySpecialSchoolSeventhGrade,
    ElementarySpecialSchoolEighthGrade,
    ElementarySpecialSchoolNinethGrade,
    ElementarySpecialSchoolTenthGrade,
    HighSchool,
    HighSchoolMultyYearPlanLowerGrade,
    ConservatorySixYearPlan,
    ConservatoryEightYearPlanLowerGrade,
    ConservatoryEightYearPlanHigherGrade,
    UniversityWithFieldOfStudy,
    College,
    ForeignSchool,
    Other,

}

public enum Rakv
{
    Student = 1,
    Interupted = 2,
    EndedWithoutCopmletion = 3,
    Completed = 4,
    AdditionalPostponment = 5,
    FailedExamByAnonymous = 6,
    PassedExamByAnonymous = 7,
    PersonHaveNotEntered = 9
}

public enum Razv
{
    AdmissionToFirstGrade = 1,
    AdmissionToThirdGradeOf6YearGymnasium ,
    AdmissionToFifthGradeOf8YearGymnasium,
    AdmissionToHigherGrade,
    TransferFromOtherSchool,
    TransferFromLowerGradeOfMultiYearGymnasiumTo4YearScopeGymnasium,
    TransferFromOtherSchoolAfterTheirMergeOrDemise,
    AdmissionOfUkraineRefugee,
    ExamBy113cOfSchoolLaw,
    ExamBy113dOfSchoolLaw
}

public enum Rako
{
    WithoutCitizenship = 0,
    CzechCitizen = 3,
    ForeignerWithPermanentResidenceInCz = 5,
    ForeignerWithoutPermanentResidenceInCz = 6,
    AsylumSeekerWithTemporaryProtectionInCz = 7,
    Uknown = 9
}


public enum Rakk
{
    WithoutEducation = 1,
    BasicEducation,
    ElementaryEducation,
    HighSchoolWithoutGraduationOrCertificate,
    HighSchoolWithCertificate,
    HighSchoolWithGraduation,
    Conservatory,
    UniversityWithFieldOfStudy,
    UniversityWithBachelorsDegree,
    UniversityWithMastersDegree,
    UniversityWithDoctoralDegree,
    EndedLastSemesterWithoutGraduation
}


public enum Rast
{
    NotYetDetected = 0,
    IslamicRepublicOfAfghanistan = 4,
    RepublicOfAlbania = 8,
    Antarctica = 10,
    DemocraticAndPeoplesRepublicOfAlgeria = 12,
    TerritoryOfAmericanSamoa = 16,
    PrincipalityOfAndorra = 20,
    RepublicOfAngola = 24,
    AntiguaAndBarbuda = 28,
    RepublicOfAzerbaijan = 31,
    ArgentineRepublic = 32,
    CommonwealthOfAustralia = 36,
    RepublicOfAustria = 40,
    CommonwealthOfTheBahamas = 44,
    KingdomOfBahrain = 48,
    PeoplesRepublicOfBangladesh = 50,
    RepublicOfArmenia = 51,
    Barbados = 52,
    KingdomOfBelgium = 56,
    Bermuda = 60,
    KingdomOfBhutan = 64,
    MultinationalStateOfBolivia = 68,
    BosniaAndHerzegovina = 70,
    RepublicOfBotswana = 72,
    BouvetIsland = 74,
    FederativeRepublicOfBrazil = 76,
    Belize = 84,
    BritishIndianOceanTerritory = 86,
    SolomonIslands = 90,
    BritishVirginIslands = 92,
    RepublicOfKosovo = 95,
    StateOfBruneiDarussalam = 96,
    RepublicOfBulgaria = 100,
    RepublicOfTheUnionOfMyanmar = 104,
    RepublicOfBurundi = 108,
    RepublicOfBelarus = 112,
    KingdomOfCambodia = 116,
    RepublicOfCameroon = 120,
    Canada = 124,
    RepublicOfCapeVerde = 132,
    CaymanIslands = 136,
    CentralAfricanRepublic = 140,
    DemocraticSocialistRepublicOfSriLanka = 144,
    RepublicOfChad = 148,
    RepublicOfChile = 152,
    PeoplesRepublicOfChina = 156,
    Taiwan = 158,
    ChristmasIslandTerritory = 162,
    TerritoryOfTheCocosIslands = 166,
    RepublicOfColombia = 170,
    UnionOfTheComoros = 174,
    DepartmentOfMayotte = 175,
    RepublicOfTheCongo = 178,
    DemocraticRepublicOfTheCongo = 180,
    CooksIslands = 184,
    RepublicOfCostaRica = 188,
    RepublicOfCroatia = 191,
    RepublicOfCuba = 192,
    RepublicOfCyprus = 196,
    CzechRepublic = 203,
    RepublicOfBenin = 204,
    KingdomOfDenmark = 208,
    DominicanCommunity = 212,
    DominicanRepublic = 214,
    RepublicOfEcuador = 218,
    RepublicOfElSalvador = 222,
    RepublicOfEquatorialGuinea = 226,
    FederalDemocraticRepublicOfEthiopia = 231,
    StateOfEritrea = 232,
    RepublicOfEstonia = 233,
    FaroeIslands = 234,
    Falklands = 238,
    SouthGeorgiaAndTheSouthSandwichIslands = 239,
    RepublicOfFiji = 242,
    RepublicOfFinland = 246,
    ProvinceOfÅland = 248,
    TheFrenchRepublic = 250,
    FrenchGuiana = 254,
    FrenchPolynesia = 258,
    FrenchSouthernAndAntarcticTerritories = 260,
    RepublicOfDjibouti = 262,
    RepublicOfGabon = 266,
    Georgia = 268,
    RepublicOfTheGambia = 270,
    PalestinianAutonomousTerritories = 275,
    TheFederalRepublicOfGermany = 276,
    RepublicOfGhana = 288,
    Gibraltar = 292,
    RepublicOfKiribati = 296,
    HellenicRepublic = 300,
    Greenland = 304,
    Grenada = 308,
    GuadeloupeRegion = 312,
    TerritoryOfGuam = 316,
    RepublicOfGuatemala = 320,
    RepublicOfGuinea = 324,
    CooperativeRepublicOfGuyana = 328,
    RepublicOfHaiti = 332,
    HeardIslandAndMacDonaldIslands = 334,
    VaticanCityState = 336,
    RepublicOfHonduras = 340,
    HongKongSpecialAdministrativeRegionOfThePeoplesRepublicOfChina = 344,
    Hungary = 348,
    RepublicOfIceland = 352,
    RepublicOfIndia = 356,
    RepublicOfIndonesia = 360,
    IslamicRepublicOfIran = 364,
    RepublicOfIraq = 368,
    Ireland = 372,
    StateOfIsrael = 376,
    ItalianRepublic = 380,
    RepublicOfIvoryCoast = 384,
    Jamaica = 388,
    Japan = 392,
    RepublicOfKazakhstan = 398,
    HashemiteKingdomOfJordan = 400,
    RepublicOfKenya = 404,
    DemocraticPeoplesRepublicOfKorea = 408,
    TheKoreanRepublic = 410,
    StateOfKuwait = 414,
    KyrgyzRepublic = 417,
    LaoPeoplesDemocraticRepublic = 418,
    RepublicOfLebanon = 422,
    KingdomOfLesotho = 426,
    RepublicOfLatvia = 428,
    RepublicOfLiberia = 430,
    LibyanState = 434,
    PrincipalityOfLiechtenstein = 438,
    RepublicOfLithuania = 440,
    GrandDuchyOfLuxembourg = 442,
    MacaoSpecialAdministrativeRegionOfThePeoplesRepublicOfChina = 446,
    RepublicOfMadagascar = 450,
    RepublicOfMalawi = 454,
    Malaysia = 458,
    RepublicOfMaldives = 462,
    RepublicOfMali = 466,
    RepublicOfMalta = 470,
    Martinique = 474,
    IslamicRepublicOfMauritania = 478,
    RepublicOfMauritius = 480,
    UnitedMexicanStates = 484,
    PrincipalityOfMonaco = 492,
    Mongolia = 496,
    RepublicOfMoldova = 498,
    Montenegro = 499,
    Montserrat = 500,
    KingdomOfMorocco = 504,
    RepublicOfMozambique = 508,
    SultanateOfOman = 512,
    RepublicOfNamibia = 516,
    RepublicOfNauru = 520,
    FederalDemocraticRepublicOfNepal = 524,
    Netherlands = 528,
    TheCountryOfCuraçao = 531,
    Aruba = 533,
    SaintMartin = 534,
    Bonaire = 535,
    NewCaledonia = 540,
    RepublicOfVanuatu = 548,
    NewZealand = 554,
    RepublicOfNicaragua = 558,
    NigerRepublic = 562,
    FederalRepublicOfNigeria = 566,
    Niue = 570,
    NorfolkTerritory = 574,
    KingdomOfNorway = 578,
    CommunityOfTheNorthernMarianaIslands = 580,
    SmallerOutlyingIslandsOfTheUSA = 581,
    FederatedStatesOfMicronesia = 583,
    RepublicOfTheMarshallIslands = 584,
    RepublicOfPalau = 585,
    IslamicRepublicOfPakistan = 586,
    RepublicOfPanama = 591,
    TheIndependentStateOfPapuaNewGuinea = 598,
    RepublicOfParaguay = 600,
    RepublicOfPeru = 604,
    RepublicOfThePhilippines = 608,
    PitcairnIslands = 612,
    PolishRepublic = 616,
    PortugueseRepublic = 620,
    RepublicOfGuineaBissau = 624,
    DemocraticRepublicOfEastTimor = 626,
    CommonwealthOfPuertoRico = 630,
    StateOfQatar = 634,
    RéunionRegion = 638,
    Romania = 642,
    RussianFederation = 643,
    RepublicOfRwanda = 646,
    CommunityOfSaintBartholomew = 652,
    SaintHelena = 654,
    FederationOfSaintKittsAndNevis = 659,
    Anguilla = 660,
    SaintLucia = 662,
    SaintMartinCommunity = 663,
    TerritorialCommunityOfSaintPierreAndMiquelon = 666,
    SaintVincentAndTheGrenadines = 670,
    RepublicOfSanMarino = 674,
    DemocraticRepublicOfSãoToméAndPríncipe = 678,
    KingdomOfSaudiArabia = 682,
    RepublicOfSenegal = 686,
    RepublicOfSerbia = 688,
    RepublicOfSeychelles = 690,
    RepublicOfSierraLeone = 694,
    RepublicOfSingapore = 702,
    SlovakRepublic = 703,
    SocialistRepublicOfVietnam = 704,
    RepublicOfSlovenia = 705,
    FederalRepublicOfSomalia = 706,
    SouthAfricanRepublic = 710,
    RepublicOfZimbabwe = 716,
    KingdomOfSpain = 724,
    RepublicOfSouthSudan = 728,
    RepublicOfSudan = 729,
    SahrawiArabDemocraticRepublic = 732,
    RepublicOfSuriname = 740,
    SvalbardAndJanMayen = 744,
    KingdomOfSwaziland = 748,
    KingdomOfSweden = 752,
    TheSwissConfederation = 756,
    SyrianArabRepublic = 760,
    RepublicOfTajikistan = 762,
    KingdomOfThailand = 764,
    RepublicOfTogo = 768,
    Tokelau = 772,
    KingdomOfTonga = 776,
    RepublicOfTrinidadAndTobago = 780,
    TheStateOfTheUnitedArabEmirates = 784,
    RepublicOfTunisia = 788,
    RepublicOfTurkey = 792,
    Turkmenistan = 795,
    TurksAndCaicosIslands = 796,
    Tuvalu = 798,
    RepublicOfUganda = 800,
    Ukraine = 804,
    RepublicOfNorthMacedonia = 807,
    ArabRepublicOfEgypt = 818,
    UnitedKingdomOfGreatBritainAndNorthernIreland = 826,
    BailiwickOfGuernsey = 831,
    BailiwickOfJersey = 832,
    IsleOfMan = 833,
    UnitedRepublicOfTanzania = 834,
    UnitedStatesOfAmerica = 840,
    USVirginIslands = 850,
    BurkinaFaso = 854,
    EasternRepublicOfUruguay = 858,
    RepublicOfUzbekistan = 860,
    BolivarianRepublicOfVenezuela = 862,
    TerritoryOfTheWallisIslandsAndFutuna = 876,
    TheIndependentStateOfSamoa = 882,
    RepublicOfYemen = 887,
    RepublicOfZambia = 894,
    Other = 999

}


public enum Raro
{
    FirstGrade = 1,
    SecondGrade,
    ThirdGrade,
    FourthGrade,
    FifthGrade,
    SixthGrade,
    SeventhGrade,
    EightGrade,
    NinthGrade,
    TenthGrade,
    GradeNotAssigned,
}

//translate
public enum Razn
{
    NoDisadvantages = 1,
    ShortTermDisadvantages,
    LongTermDisadvantages,
    LightMentalIllness,
    IntermediateMentalIllness,
    HeavyMentalIllness,
    DeepMentalIllness,
    LightlyDeaf,
    HeavilyDeaf,
    Deaf,
    LightlyBlind,
    IntermediatlyBlind,
    HeavilyBlind,
    Blind,
    LightSpeechDefect,
    IntermediateSpeechDefect,
    HeavySpeechDefect,
    LightPhysicalDisability,
    IntermediatePhysicalDisability,
    HeavyPhysicalDisability,
    LightBehaviourDisorder,
    IntemediateBehaviourDisorder,
    HeavyBehaviourDisorder,
    LightLearningDisorder,
    IntermediateLearningDisorder,
    OffADS,
    LightADS,
    KidAutism

}